CREATE TABLE address_entity
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    country     VARCHAR(255)                            NOT NULL,
    city        VARCHAR(255)                            NOT NULL,
    street      VARCHAR(255)                            NOT NULL,
    postal_code VARCHAR(255)                            NOT NULL,
    state       VARCHAR(255)                            NOT NULL,
    consumer_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_addressentity PRIMARY KEY (id)
);

CREATE TABLE consumer_entity
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    first_name   VARCHAR(255)                            NOT NULL,
    last_name    VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    phone_number VARCHAR(255)                            NOT NULL,
    active       BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_consumerentity PRIMARY KEY (id)
);

CREATE TABLE merchant_entity
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name       VARCHAR(255),
    CONSTRAINT pk_merchantentity PRIMARY KEY (id)
);

CREATE TABLE parcel_entity
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    length         INTEGER                                 NOT NULL,
    width          INTEGER                                 NOT NULL,
    height         INTEGER                                 NOT NULL,
    weight         DOUBLE PRECISION                        NOT NULL,
    description    VARCHAR(255)                            NOT NULL,
    parcel_status  VARCHAR(255)                            NOT NULL,
    tariff_type    VARCHAR(255)                            NOT NULL,
    active         BOOLEAN,
    price          DOUBLE PRECISION                        NOT NULL,
    distance       DOUBLE PRECISION                        NOT NULL,
    latitude_from  DOUBLE PRECISION                        NOT NULL,
    longitude_from DOUBLE PRECISION                        NOT NULL,
    latitude_to    DOUBLE PRECISION                        NOT NULL,
    longitude_to   DOUBLE PRECISION                        NOT NULL,
    address_id     BIGINT,
    merchant_id    BIGINT                                  NOT NULL,
    consumer_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_parcelentity PRIMARY KEY (id)
);

CREATE TABLE price_entity
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    tariff_type VARCHAR(255)                            NOT NULL,
    price       DOUBLE PRECISION                        NOT NULL,
    active      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_priceentity PRIMARY KEY (id)
);

ALTER TABLE consumer_entity
    ADD CONSTRAINT uc_consumerentity_email UNIQUE (email);

ALTER TABLE consumer_entity
    ADD CONSTRAINT uc_consumerentity_phonenumber UNIQUE (phone_number);

ALTER TABLE address_entity
    ADD CONSTRAINT FK_ADDRESSENTITY_ON_CONSUMER FOREIGN KEY (consumer_id) REFERENCES consumer_entity (id);

ALTER TABLE parcel_entity
    ADD CONSTRAINT FK_PARCELENTITY_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address_entity (id);

ALTER TABLE parcel_entity
    ADD CONSTRAINT FK_PARCELENTITY_ON_CONSUMER FOREIGN KEY (consumer_id) REFERENCES consumer_entity (id);

ALTER TABLE parcel_entity
    ADD CONSTRAINT FK_PARCELENTITY_ON_MERCHANT FOREIGN KEY (merchant_id) REFERENCES merchant_entity (id);